appTitle: WG Dashboard

pages:
  dashboard: true
  photoBooth: true
  photoBoothGallery: true
  people: true
  settings: true

dashboard:
  holidayCountry: CH

  cards:
    trash: true
    weatherOutfit: true

  sbbBus:
    from: "8590930"
    to: "8506000"
    limit: 10

  weather:
    enabled: true
    provider: openMeteo
    latitude: 47.3769
    longitude: 8.5417
    timezone: Europe/Zurich

chores:
  rotation:
    type: monthly

  startDate: "2025-01-01"

  people:
    - name: Nando
      birthday: "18.12.2000"
      img: /people/nando-1.jpg
      altImg: /people/nando-2.jpg

    - name: Michelle
      birthday: "04.11.1998"
      img: /people/timon-1.jpg
      altImg: /people/timon-2.webp

    - name: Timon
      birthday: "25.11.1999"
      img: /people/michelle-1.jpg
      altImg: /people/michelle-2.webp

  items:
    - id: bathroom
      icon: poop

    - id: floor
      icon: broom

    - id: kitchen
      icon: cutlery